### ISSUE TITLE
Test suite may fail (hash randomization?)

### ISSUE THREAD

**Issue by eserte** [Chipsoid/yandex-oauth-perl#1]
For perls >= 5.18.0 the test suite may fail. See http://matrix.cpantesters.org/?dist=Yandex-OAuth%200.05 for a pass/fail overview.

A test failure looks like this:
```
#   Failed test 'prepare_request body'
#   at t/02_client.t line 29.
#          got: '{"param1":"value1","param2":2}'
#     expected: '{"param2":2,"param1":"value1"}'
# Looks like you failed 1 test of 11.
t/02_client.t ...
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/11 subtests
```
... which looks like hash randomization is causing the problem. You probably have to canonify the compared values.

**Comment by Chipsoid** [comment]
thanks for your comment.
I use functions "is", but need "is_deeply" for hashes.

**Comment by eserte** [comment]
Unfortunately 0.06 has the same problem. Maybe it's something different --- missing canonization in the json output?

**Comment by wa-pis** [comment]
https://github.com/Chipsoid/yandex-oauth-perl/pull/2

**Comment by eserte** [comment]
0.07 looks good.
